# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
avatar = "https://webp.debuginn.com/20250929bC0ReU.jpg"
# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy = "default"

[footer]
since = 2017
customText = '<a href="https://debuginn.com" target="_blank">主页</a>&nbsp;·&nbsp<a href="https://blog.debuginn.com/">博客</a>&nbsp;·&nbsp<a href="https://photo.debuginn.com" target="_blank">摄影</a>&nbsp;·&nbsp<a href="/subscribe/">订阅</a>&nbsp;·&nbsp<a href="/project/">项目</a>&nbsp;·&nbsp<a href="/use/">使用</a>&nbsp;·&nbsp<a href="/reward/">赞赏</a>&nbsp;·&nbsp<a href="/about/">关于</a>'

[dateFormat]
published = ":date_full"
lastUpdated = ":date_full"

[sidebar]
emoji = "🌏"
subtitle = "永远相信美好的事情即将发生"
avatar = "https://webp.debuginn.com/20250929bC0ReU.jpg"

[article]
headingAnchor = true
math = false
toc = true
readingTime = true

[article.license]
enabled = true
default = "本作品采用知识共享署名 - 非商业性使用 - 相同方式共享 4.0 许可协议进行许可，商业转载请联系授权。"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "wechat"

[[widgets.homepage]]
type = "popular"

[[widgets.homepage]]
type = "promote"

[[widgets.homepage]]
type = "email"

[[widgets.homepage]]
type = "donation"

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 32

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 3

[[widgets.page]]
type = "search"

[[widgets.page]]
type = "wechat"

[[widgets.page]]
type = "toc"

[[widgets.page]]
type = "email"

[[widgets.page]]
type = "donation"

[[widgets.page]]
type = "promote"

[[widgets.page]]
type = "popular"

# [[widgets.page]]
# type = "ad"

[opengraph.twitter]
site = "idebuginn"
card = "summary_large_image"

[defaultImage]
opengraph = "https://static.debuginn.com/20250506fT6oPc.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "debuginn/blog"
repoID = "R_kgDOI_rNgg"
category = "General"
categoryID = "DIC_kwDOI_rNgs4CUT4j"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0
lang = "zh-CN"

[donation]
title = "赞赏"
qrcode = "https://static.debuginn.com/20250807C6FEAA.png"
link = "/reward/"

[[donation.cryptos]]
label = "ETH"
address = "0xd06a56704ecb1eee65abcaa3101d88e2a8225a4e"
donate = true
amount = 0.001
icon = "currency-ethereum"

[[donation.cryptos]]
label = "SOL"
address = "5LupLo8NuTfC411zAPo6UZTuasoTHaueuptVyGKmsdBV"
icon = "currency-solana"

[promote]
title = "推广"

# [[promote.items]]
# href = "/p/mi-work/"
# icon = "briefcase"
# text = "来小米，一起玩！校招、社招均可内推！"

[[promote.items]]
href = "https://xflash.org/#/register?code=yGSImRR7"
icon = "network"
text = "XFlash Cloud 稳定好用速度快节点多"
target = "_blank"

[[promote.items]]
href = "https://app.cloudcone.com/?ref=13045"
icon = "cloud-network"
text = "CloudCone VPS 每月仅需 $1.66"
target = "_blank"

[popular]
title = "热门"

[[popular.items]]
href = "https://flybay.debuginn.com/"
icon = "plane"
text = "飞湾计划 通过开户补贴报销来往机票"
target = "_blank"

[[popular.items]]
href = "/categories/travel/"
icon = "building-airport"
text = "游记系列 跟我一起环游中国"

[email]
title = "订阅"
placeholder = "输入邮箱，获取最新文章推送"
buttonText = "订阅"
mailchimpUrl = "https://us3.list-manage.com/subscribe/post-json"
u = "397828d3cf4dbe2593b9da8e3"
id = "b7404a6937"

# [ad]
# title = "广告"
